spring: 
 profiles:
  active:
   - dev
---
spring:
 profiles: dev
 application:
  name: microservice-cloud-config-mezj-dev
---
spring:
 profiles: test
 application: 
  name: microservice-cloud-config-mezj-test