spring:
 profiles:
  active:
   - dev
---
server:
 port: 8201

spring:
 profiles: dev
 application:
  name: microservice-cloud-config-client

eureka:
 client:
  service-uri:
   defaultZone: http://eureka-dev:7001/eureka/
---
server:
 port: 8202
spring:
 profiles: test
 application:
  name: microservice-cloud-config-client
eureka:
 client:
 service-uri:
  defaultZone: http://eureka-test:7001/eureka/